" General options we like everywhere

" Setup pathogen
call pathogen#infect()
call pathogen#helptags()

" Don't be like vi
set nocompatible

" 256 colors
set t_Co=256

" Tab and Indent Settings
set autoindent
set tabstop=4 shiftwidth=4 softtabstop=4
set noexpandtab
set smarttab
set smartindent

set pastetoggle=<F5> " toggle paste mode

" Line numbers
set nu " Line numbers on
nnoremap <F6> :set nonumber!<CR> " toggle line numbers

set ruler " Ruler on

set hlsearch      " highlight search terms
set incsearch     " search as you type

set ignorecase
set smartcase     " case-smart searching

" File-type highlighting and configuration
syntax on
filetype on
filetype plugin on
filetype indent on

" default colorscheme
colorscheme railscasts

" more useful tab completion
set wildmenu
set wildmode=list:longest

" Keep all tmp files in a central location
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp

" Shed light on hidden things
"set list
"set listchars=tab:»»,trail:•
set listchars=trail:•
"set wrap
"set linebreak
"set showbreak=↳

" Highlight trailing whitespace characters and tabs not used for indention
"highlight WhitespaceErrors ctermbg=Red guibg=Red
"match WhitespaceErrors /\s\+$\|[^\t]\@<=\t\+/

" Remove trailing whitespace
noremap <silent> <Leader>rtw :%s/\s\+$//g<CR>``

" alias for NERDTree command
command NT NERDTree

"ruby
autocmd FileType ruby,eruby set omnifunc=rubycomplete#Complete
autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading = 1
autocmd FileType ruby,eruby let g:rubycomplete_rails = 1
autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global = 1
"improve autocomplete menu color
highlight Pmenu ctermbg=238 gui=bold
